# Site settings
title: "Amir H. Jadidinejad"
description: "Amir H. Jadidinejad resume portfolio website"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Amir H. Jadidinejad"
resume_title:                   "Machine Learning Engineer"
resume_contact_email:
  "amir.jadidi@yahoo.com"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/amirj"
  resume_twitter_url:           "http://twitter.com/jadidinejad"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "http://www.linkedin.com/in/jadidinejad"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://amirj.github.io"

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
